on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  document-qa:
    runs-on: ubuntu-latest
    name: WG Document QA
    steps:
      - uses: actions/checkout@v2
      - uses: afrinic-dbwg/document-qa@release

